services:
  flynotify:
    build:
      context: /share/Container/flynotify
      dockerfile: Dockerfile
      network: host
    container_name: flynotify
    ports:
      - "8085:8080"
    volumes:
      - /share/Container/flynotify/data:/app/data
    environment:
      - TZ=Australia/Sydney
      - Scheduler__Hour=10
      - Scheduler__Minute=0
      - Scraper__UseMockData=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
    restart: always
