services:
  flynotify:
    image: flynotify:latest
    pull_policy: never
    container_name: flynotify
    ports:
      - "8085:8080"
    volumes:
      - /share/Container/flynotify/data:/app/data
    environment:
      - TZ=Australia/Sydney
      - Scheduler__TimeZone=Australia/Sydney
      - Scheduler__HourUtc=0
      - Scheduler__MinuteUtc=0
      - Scheduler__SecondUtc=15
      - Scraper__UseMockData=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
    restart: always
